# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/TEMP_Work/vivado_work/pipeline_same/pipeline_same.srcs/sources_1/ip/data_ram/data_ram.xci
# IP: The module: 'data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/TEMP_Work/vivado_work/pipeline_same/pipeline_same.srcs/sources_1/ip/data_ram/data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/TEMP_Work/vivado_work/pipeline_same/pipeline_same.srcs/sources_1/ip/data_ram/data_ram.xci
# IP: The module: 'data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/TEMP_Work/vivado_work/pipeline_same/pipeline_same.srcs/sources_1/ip/data_ram/data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
