# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/TEMP_Work/vivado_work/pipeline_cpu/pipeline_cpu.srcs/sources_1/ip/inst_rom/inst_rom.xci
# IP: The module: 'inst_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/TEMP_Work/vivado_work/pipeline_cpu/pipeline_cpu.srcs/sources_1/ip/inst_rom/inst_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/TEMP_Work/vivado_work/pipeline_cpu/pipeline_cpu.srcs/sources_1/ip/inst_rom/inst_rom.xci
# IP: The module: 'inst_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/TEMP_Work/vivado_work/pipeline_cpu/pipeline_cpu.srcs/sources_1/ip/inst_rom/inst_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
